name: yourtour
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  lottie: ^2.7.0
  smooth_page_indicator: ^1.1.0
  confetti: ^0.7.0
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  dio: ^5.4.1
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  geolocator: ^10.0.0
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  text_to_speech: ^0.2.3
  share_plus: ^10.0.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/badges/
    # Add animations directory
    - assets/animations/