# github actions workflow for flutter

name: Flutter

# https://github.com/subosito/flutter-action/discussions/197
env:
  RUNNER_OS: macos

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    branches:
      - main
      - master
      - dev

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Fix flutter SDK folder permission
        run: git config --global --add safe.directory /tmp/flutter/--

      - name: Clone repository
        uses: actions/checkout@v4
  
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.1
        
      - name: Install dependencies
        run: flutter pub get

      - name: Freeze providers
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Test
        run: flutter test

      - name: Build app
        run: flutter build ios --release --no-codesign
